version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env.docker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - adopcion_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - adopcion_network
    volumes:
      - .:/app

networks:
  adopcion_network:
    driver: bridge

volumes:
  mysql_data: